theme: jekyll-theme-slate

show_downloads: true

github:
  zip_url: https://github.com/mkschleg/GVFN/archive/master.zip
  tar_url: https://github.com/mkschleg/GVFN/archive/master.zip
  arxiv_url: https://arxiv.org/abs/1807.06763
