[config]
save_dir="critterbot_rnn"
exp_file="experiment/timeseries.jl"
exp_module_name = "TimeSeriesExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
"env" = "Critterbot"
"horizon" = 12
"steps" = 119000
"valSteps" = 100
"testSteps" = 100
"observation_sensors" = [31, 32, 33]
"target_sensors" = [31, 32, 33]

"agent" = "RNN"
"rnn_cell" = "RNN"
"rnn_nhidden" = 128
"rnn_opt" = "ADAM"
"rnn_beta1" = 0.99
"rnn_beta2" = 0.999
"update_fn" = "BatchTD"
"batchsize" = 32

"model_clip_coeff" = 0.25

[sweep_args]
"rnn_lr" = "collect(2.0.^(-20:-1))"
"activation" = ["bounded1","bounded5","bounded10","tanh"]
"rnn_tau" = [1,2,4,8,16,32]
"seed" = "1:30"
