[config]
save_dir="critterbot_rnn"
exp_file="experiment/critterbot.jl"
exp_module_name = "CritterbotExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
"env" = "Critterbot"

"steps" = 119000
"observation_sensors" = ["IR0", "IR2", "IR3"]
"target_sensors" = ["Light3"]

"agent" = "RNN"
"rnn_cell" = "RNN"
"rnn_nhidden" = 128
"rnn_opt" = "ADAM"
"rnn_beta1" = 0.99
"rnn_beta2" = 0.999
"update_fn" = "BatchTD"
"batchsize" = 32

"model_clip_coeff" = 0.25

"activation" = "tanh"

"tilings" = 8
"tiles" = 8

[sweep_args]
"rnn_lr" = "collect(2.0.^(-20:-1))"
# "rnn_lr" = [0.001]
# "activation" = ["bounded1","bounded5","bounded10","tanh"]
"rnn_tau" = [1, 2, 4, 8, 16, 32, 64]
"horizon" = [60, 200]
"seed" = "1:30"
