[config]
save_dir="critterbot_tpc_tc"
exp_file="experiment/critterbot_tpc.jl"
exp_module_name = "CritterbotTPCExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
"env" = "Critterbot"

"steps" = 119000
"observation_sensors" = ["IR0", "IR2", "IR3"]

"agent" = "Tilecoder"
"rnn_cell" = "RNN"
"rnn_nhidden" = 128
"rnn_opt" = "Descent"
"rnn_beta1" = 0.99
"rnn_beta2" = 0.999
"update_fn" = "BatchTD"
"batchsize" = 32

"model_clip_coeff" = 100.0

"tilings" = 8
"tiles" = 8
"horizon" = 1

[sweep_args]
"rnn_lr" = "collect(2.0.^(-10:-1))"
"rnn_tau" = [1]
"seed" = "1:10"