[config]
save_dir="mackeyglass_gvfn_small"
exp_file="experiment/timeseries.jl"
exp_module_name = "TimeSeriesExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"


[static_args]
"env" = "MackeyGlass"
"horizon" = 12
"steps" = 600000
"valSteps" = 200000
"testSteps" = 200000

"agent" = "GVFN"
"update_fn" = "BatchTD"
"batchsize" = 32
"gamma_low" = 0.2
"gamma_high" = 0.95
"base_exponent" = 2.0
"horde" = "LinSpacing"

"gvfn_opt" = "Descent"
"model_opt" = "ADAM"
"base_exponent" = 2.0

"model_clip_coeff" = 0.25

[sweep_args]
"gvfn_stepsize" = [1e-6,5e-6,0.00001, 0.00005, 0.0001, 0.0005, 0.001, 0.005]
"model_stepsize" = [0.00001, 0.00005, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05]
"activation" = ["bounded10"]

"num_gvfs" = [4, 8]

"gvfn_tau" = [1,2,4,8,16,32]
"seed" = "1:30"

