[config]
save_dir="mackeyglass_rnn_orig"
exp_file="experiment/timeseries.jl"
exp_module_name = "TimeSeriesExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
"env" = "MackeyGlass"
"horizon" = 12
"steps" = 600000
"valSteps" = 200000
"testSteps" = 200000

"agent" = "RNN"
"rnn_cell" = "GRU"
"rnn_opt" = "ADAM"
"update_fn" = "BatchTD"
"batchsize" = 32

"model_clip_coeff" = 0.25

[sweep_args]
"rnn_lr" = [0.01, 0.001, 0.003, 0.0001, 0.0003]
"rnn_nhidden" = [32,64,128]

"rnn_tau" = [1,2,4,8,16,32]
"seed" = "1:10"