[config]
save_dir="mso_rnn_normalized"
exp_file="experiment/timeseries.jl"
exp_module_name = "TimeSeriesExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
"env" = "MSO"
"horizon" = 12
"steps" = 600000
"valSteps" = 200000
"testSteps" = 200000

"agent" = "RNN"
"rnn_cell" = "GRU"
"rnn_opt" = "ADAM"
"rnn_beta1" = 0.9
"rnn_beta2" = 0.999
"update_fn" = "BatchTD"
"batchsize" = 32

"normalizer"="Unity"
"max" = 3.6442
"min" = -3.6442

"model_clip_coeff" = 0.25

[sweep_args]
"rnn_lr" = "collect(2.0.^(-20:-1))"
"rnn_nhidden" = [32,64,128]
"rnn_tau" = [1,2,4,8,16,32]
"seed" = "1:10"
