[config]
save_dir="mso_gvfn_relu_orig"
exp_file="experiment/timeseries.jl"
exp_module_name = "TimeSeriesExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"


[static_args]
"env" = "MSO"
"horizon" = 12
"steps" = 600000
"valSteps" = 200000
"testSteps" = 200000

"agent" = "GVFN"
"activation" = "relu"
"update_fn" = "BatchTD"
"batchsize" = 32

"horde" = "LinSpacing"
"gamma_low" = 0.1
"gamma_high" = 0.9
"num_gvfs" = 128

"gvfn_opt" = "Descent"
"model_opt" = "ADAM"

"model_clip_coeff" = 0.25

[sweep_args]
"gvfn_stepsize" = [0.00001, 0.00003, 0.0001, 0.0003]
"model_stepsize" = [0.0001, 0.0003, 0.001, 0.003]

"gvfn_tau" = [1,2,4,8,16,32]
"seed" = "1:10"

