[config]
save_dir="mso_gvfn_best"
exp_file="experiment/timeseries.jl"
exp_module_name = "TimeSeriesExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
"env" = "MSO"
"horizon" = 12
"steps" = 600000
"valSteps" = 200000
"testSteps" = 200000

"agent" = "GVFN"
"activation" = "linear"
"update_fn" = "BatchTD"
"batchsize" = 32

"horde" = "LinSpacing"
"num_gvfs" = 128
"gamma_low" = 0.1
"gamma_high" =  0.97

"gvfn_opt" = "Descent"
"gvfn_stepsize" = 3e-4
"model_stepsize" = 0.0001
"model_opt" = "ADAM"
"model_clip_coeff" = 0.25
"normalizer" = "IncrementalUnity"
"gvfn_tau" = 1

[sweep_args]
"seed" = "1:1"

