[config]
save_dir="mso_aux_rnn"
exp_file="experiment/timeseries.jl"
exp_module_name = "TimeSeriesExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
"env" = "MSO"
"horizon" = 12
"steps" = 600000
"valSteps" = 200000
"testSteps" = 200000

"agent" = "AuxTasks"
"rnn_nhidden" = 128
"rnn_cell" = "RNN"
"rnn_opt" = "ADAM"
"rnn_beta1" = 0.9
"rnn_beta2" = 0.999
"update_fn" = "BatchTD"
"batchsize" = 32

"horde" = "LinSpacing"
"gamma_low" = 0.2
"gamma_high" = 0.95
"num_gvfs" = 128

"model_clip_coeff" = 0.25

[sweep_args]
"rnn_lr" = "collect(2.0.^(-20:-1))"
"activation" = ["bounded1","bounded5","bounded10","tanh"]
"rnn_tau" = [1,2,4,8,16,32]
"seed" = "1:10"
