
[config]
save_dir="compassworld_gvfn_rmsprop"
exp_file="experiment/compassworld.jl"
exp_module_name = "CompassWorldExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
"size" = 8
"steps" = 1000000
"opt" = "RMSProp"
"out-horde" = "forward"
"sweep" = true
"policy" = "rafols"

[sweep_args]
"activation" = ["sigmoid"]
"gvfn-horde" = ["rafols", "forward", "gammas_aj", "gammas_aj_term"]
"alpha" = "clamp.(0.01*1.5.^(-10:2:1), 0.0, 1.0)"
"truncation" = [1, 4, 8, 12, 16, 24, 32]
"seed" = "1:10"