[config]
save_dir="compassworld_rnn_aux_task"
exp_file="experiment/compassworld_aux_task.jl"
exp_module_name = "CompassWorldExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
"size" = 8
"steps" = 1000000
"opt" = "Descent"
"out-horde" = "forward"
"sweep" = true
"policy" = "rafols"

[sweep_args]
"activation" = ["sigmoid"]
"cell" = ["ARNN", "GRU", "LSTM"]
"at-horde" = ["rafols", "gammas_aj_term"]
"hidden" = [40]
"alpha" = "clamp.(0.1*1.5.^(-10:6), 0.0, 1.0)"
"truncation" = [1, 4, 8, 12, 16, 24, 32]
"seed" = "1:10"