[config]
save_dir="acea_gvfn"
exp_file="experiment/timeseries.jl"
exp_module_name = "TimeSeriesExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"


[static_args]
"env" = "ACEA"
"horizon" = 144
"steps" = 60000
"valSteps" = 20000
"testSteps" = 20000

"agent" = "GVFN"
"update_fn" = "BatchTD"
"batchsize" = 32

"horde" = "LinSpacing"
"gamma_low" = 0.1
"gamma_high" = 0.97
"num_gvfs" = 64

"gvfn_opt" = "Descent"
"model_opt" = "ADAM"

"model_clip_coeff" = 0.25
"normalizer" = "Unity"
"max" = 109.075
"min" = 3.9

[sweep_args]
"gvfn_stepsize" = [1e-6, 5e-6,0.00001, 0.00005, 0.0001, 0.0005, 0.001, 0.005]
"model_stepsize" = [0.00001, 0.00005, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05]
"activation" = ["bounded1","bounded5","bounded10"]

"gvfn_tau" = [1,2,4,8,16,32]
"seed" = "1:10"

