[config]
save_dir="acea_rnn"
exp_file="experiment/timeseries.jl"
exp_module_name = "TimeSeriesExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
"env" = "ACEA"
"horizon" = 144
"steps" = 60000
"valSteps" = 20000
"testSteps" = 20000

"agent" = "RNN"
"rnn_opt" = "ADAM"
"update_fn" = "BatchTD"
"batchsize" = 32

"model_clip_coeff" = 0.25
"normalizer" = "Unity"
"max" = 109.075
"min" = 3.9

[sweep_args]
"rnn_lr" = "collect(2.0.^(-20:-1))"
"rnn_cell" = ["GRU","LSTM"]
"rnn_nhidden" = [32,64,128]
"rnn_tau" = [1,2,4,8,16,32]
"seed" = "1:10"
