[config]
save_dir="mackeyglass_fluxrnn"
exp_file="experiment/timeseries.jl"
exp_module_name = "TimeSeriesExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"


[static_args]
"env" = "MackeyGlass"
"horizon" = 12
"steps" = 600000
"valSteps" = 200000
"testSteps" = 200000

"agent" = "FluxRNN"
"update_fn" = "TD"
"normalizer" = "IncrementalUnity"
"opt" = "ADAM"

[sweep_args]
"cell" = ["GRU", "LSTM"]
"nhidden" = [32, 64, 128]
"stepsize" = "clamp.(2.0.^(-20:-5), 0.0, 1.0)"
"tau" = [1, 2, 4, 8, 16, 32]
"seed" = "1:10"

