[config]
save_dir="mackeyglass_gvfn_separateOpt_tau1_relu"
exp_file="experiment/timeseries.jl"
exp_module_name = "TimeSeriesExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
"env" = "MackeyGlass"
"horizon" = 12
"steps" = 600000
"valSteps" = 200000
"testSteps" = 200000

"agent" = "GVFN"
"activation" = "relu"
"update_fn" = "BatchTD"
"batchsize" = 32

"horde" = "LinSpacing"
"gamma_low" = 0.1
"gamma_high" = 0.97
"num_gvfs" = 128

"gvfn_opt" = "Descent"
"model_opt" = "ADAM"
"gvfn_tau" = 1

[sweep_args]
"gvfn_stepsize" = [0.00001,0.00005,0.0001,0.0005,0.001,0.005]
"model_stepsize" = [0.00001,0.00005,0.0001,0.0005,0.001,0.005]
"seed" = "1:10"

