[config]
save_dir="ringworld_gvfn"
exp_file="experiment/ringworld.jl"
exp_module_name = "RingWorldExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
"size" = 6
"steps" = 300
"opt" = "Descent"
"outhorde" = "gammas_term"
"outgamma" => 0.9
"gamma" = 0.95
"sweep" = false

[sweep_args]
"activation" = ["sigmoid"]
"horde" = ["gamma_chain", "chain", "gammas_aj"]
"alpha" = "clamp.(0.1*1.5.^(-6:4), 0.0, 1.0)"
"truncation" = [1, 2, 3, 4, 6, 8, 12, 16]
"seed" = "1:10"