[config]
save_dir="ringworld_rnn_adam"
exp_file="experiment/ringworld.jl"
exp_module_name = "RingWorldExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
"steps" = 300000
"opt" = "ADAM"
"outgamma" = 0.0
"gamma" = 0.95
"sweep" = true

[sweep_args]
"size" = [6, 10]
"outhorde" = ["gammas_term", "onestep"]
"cell" = ["ARNN", "GRU", "LSTM"]
"alpha" = "clamp.(0.01*1.5.^(-10:2:1), 0.0, 1.0)"
"truncation" = [1, 2, 3, 4, 6, 8, 12, 16]
"seed" = "1:10"