[config]
save_dir="/home/mkschleg/scratch/GVFN/ringworld_gvfn"
exp_file="experiment/ringworld.jl"
exp_module_name = "RingWorldExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
"steps" = 300000
"opt" = "Descent"
"outgamma" = 0.0
"gamma" = 0.95
"sweep" = true

[sweep_args]
"size" = [6, 10]
"activation" = ["sigmoid"]
"outhorde" = ["gammas_term", "onestep"]
"horde" = ["gamma_chain", "chain", "gammas_aj", "gammas_term"]
"alpha" = "clamp.(0.1*1.5.^(-6:4), 0.0, 1.0)"
"truncation" = [1, 2, 3, 4, 6, 8, 12, 16]
"seed" = "1:10"